requires 'Template';
requires 'MooX::Singleton';
requires 'Pod::Manual';
requires 'Dancer::Plugin::Database';
requires 'Faker';
requires 'Term::ReadLine';
requires 'Tie::IxHash';
requires 'Term::UI';
requires 'Test::MockTime';
requires 'DBIx::Class::Helper::ResultSet::Random';
requires 'DBIx::Class::Result::Validation';
requires 'Data::Generate';
requires 'Hash::Merge::Simple';
requires 'Time::ParseDate';
requires 'Time::Format';
requires 'DateTime::Tiny';
requires 'Term::ProgressBar';
requires 'Array::Utils';
requires 'XML::XPath';
requires 'XML::XPath::Node';
requires 'Math::Random::MT::Auto';
requires 'XML::LibXML';
requires 'XML::XPathScript';
requires 'Pod::Manual';
requires 'Class::XSAccessor' , '1.18';
requires 'Time::Duration::Parse';
requires 'Date::Parse';
requires 'Data::Transpose', 0.0009;
requires 'DBI';
requires 'DBD::mysql';
requires 'DBI';
requires 'DBIx::Class';
requires 'DBIx::Class::EncodedColumn';
requires 'DBIx::Class::TimeStamp';
requires 'DBIx::Class::Schema::Loader';
requires 'Dancer::Plugin::DBIC';
requires 'Dancer::Plugin::Email';
requires 'Dancer::Plugin::Auth::Extensible';
requires 'Dancer::Plugin::Auth::Extensible::Provider::DBIC';
requires 'Dancer';
requires 'Dancer::Session::Storable';
requires 'DBIx::Class::Tree::AdjacencyList';
requires 'Dancer::Plugin::Interchange6', '0.031';
requires 'Dancer::Session::DBIC';
requires 'Dancer::Template::TemplateFlute', '0.0113';
requires 'Interchange6::Schema', '0.052';
requires 'Interchange6', '0.030';
requires 'Template::Flute', '0.0113';
requires 'Scalar::MoreUtils';
requires 'String::Random';
requires 'Number::Format';
requires 'DateTime';
requires 'DateTime::Locale';
requires 'Moo';
requires 'MooX::Types::MooseLike';
requires 'Archive::Zip';
requires 'Math::Pari';
requires 'Net::SSLeay';
requires 'AnyEvent::TLS';
requires 'Plack';
requires 'Plack::Handler::Starman';
requires 'XML::Twig', '3.46';
requires 'YAML::Syck';
requires 'XSLoader';
requires 'XML::Simple';
requires 'Data::UUID';
requires 'XML::RSS';
requires 'Date::Calc';
requires 'File::MimeInfo';
