# configuration file for production environment

# only log warning and error messages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0

# cache route resolution for maximum performance
route_cache: 1

# Interchange6 shops should always use DBIC sessions,
# so there is no need to configure sessions here
#
# session: "DBIC"